{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.4/kmp_printer-2.3.4.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-js-2.3.4.klib",
          "url": "kmp_printer-js-2.3.4.klib",
          "size": 258245,
          "sha512": "7576c61dd1387b953c05d7bf9a351364bb2f71c16dd82ad7f902ec0ec4b348dd5227fe48f415bec9d5023b91254f64189fddb72a4b83fc4e929e6537ee68a796",
          "sha256": "ed288c271d02892cfdc20e0df7a0b70ed6584bc01eb9b560dae8ddb5b8918d9d",
          "sha1": "2efd72aea84d8917b69100f63f26b6a715117b5d",
          "md5": "76ab96f0c746c9667b0d9c18ef454286"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-js-2.3.4.klib",
          "url": "kmp_printer-js-2.3.4.klib",
          "size": 258245,
          "sha512": "7576c61dd1387b953c05d7bf9a351364bb2f71c16dd82ad7f902ec0ec4b348dd5227fe48f415bec9d5023b91254f64189fddb72a4b83fc4e929e6537ee68a796",
          "sha256": "ed288c271d02892cfdc20e0df7a0b70ed6584bc01eb9b560dae8ddb5b8918d9d",
          "sha1": "2efd72aea84d8917b69100f63f26b6a715117b5d",
          "md5": "76ab96f0c746c9667b0d9c18ef454286"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kmp_printer-js-2.3.4-sources.jar",
          "url": "kmp_printer-js-2.3.4-sources.jar",
          "size": 56829,
          "sha512": "0503bc3911a2d1d416d660a0b9588d240335a497a11f39ea6bbb7b70a134e7e2fa55fbbeed5780703012d127dd3f702770677c0e35aa6e60e869a818da90f1c4",
          "sha256": "812e69a14ff21b215f93cf572d432e2eb04beecd54014a7978f8a94633fc1be4",
          "sha1": "517861e717f62c74c29b40c0b67e8d82201b4d14",
          "md5": "52908b0346af9ea4d2e41b6dc48413a9"
        }
      ]
    }
  ]
}
