{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.6/kmp_printer-2.3.6.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosSimulatorArm64Main-2.3.6.klib",
          "url": "printer-iossimulatorarm64-2.3.6.klib",
          "size": 321813,
          "sha512": "d53fe629615b001c4803ea166d8cce911e9fe4a3eda7d34006441804996ab0f9f5eb01a48f7b1addf9f58ac828617568b53202c2680751d7159d453c532afa7e",
          "sha256": "1e9cdfab8f554d18bd9822414b40973d30727e94850d4c02184cf4191af5e717",
          "sha1": "35475a74c90e7513d0a79770802279df8144d08b",
          "md5": "245d0f9e1e7ebf9f294a6ffce7beb882"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmp_printer-iossimulatorarm64-2.3.6-sources.jar",
          "url": "printer-iossimulatorarm64-2.3.6-sources.jar",
          "size": 64069,
          "sha512": "747ce6de669fb7e2b855cacc0bdb45c8300399c12fd47edc8675ce343b05472c05adf4758dd1b09f9e9aeb1e6fede4d1f46bd9fcded7d4f67fd0864147262537",
          "sha256": "3587f4bf48de3b1bc811f03f28ff763bc4fd3884788a0cd82a855150ba430473",
          "sha1": "ef362163fdfcf89ce82ed79501b903183a0c1eb6",
          "md5": "7aa8cd7fd1f9ff847a2d1f9927d55b14"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-iossimulatorarm64-2.3.6-metadata.jar",
          "url": "printer-iossimulatorarm64-2.3.6-metadata.jar",
          "size": 6855,
          "sha512": "1709cf689d4cf2fed0c141a61bf01b1bd7daba81561ebab8a7c4b457ccbc8e24dbfa97d95943f860736ff3d4b0ceefc39198afb1912c5291081a581412ce670b",
          "sha256": "6e0158a9994b4a8c64a83d208036a6988b2885f66b5ce003d0b73a5cc6bfae24",
          "sha1": "3c08a972ffda68c16c37bc5f62e886636034f00a",
          "md5": "cc96e23ceb7aa8fe11d04a624fd51c78"
        }
      ]
    }
  ]
}
