{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/2.2.0/printer-2.2.0.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "printer-jvm-2.2.0.jar",
          "url": "printer-jvm-2.2.0.jar",
          "size": 204872,
          "sha512": "fff1f2249e954a7cbe8e608febdb973d0cb752350db8b2047fe7e20d3ad8ab447979b54e295477e112c01148e117108ab27254b9954680eb7af89411877916f1",
          "sha256": "37a420d09438b3e7a3319cd6e8f49623610f56b4e51e014d2966c51640d5e712",
          "sha1": "ea65a4e1cc3ea3bc44a93df978ce8403574ecd3a",
          "md5": "11e1cc41a97503ab7e9299813d13c09c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-jvm-2.2.0.jar",
          "url": "printer-jvm-2.2.0.jar",
          "size": 204872,
          "sha512": "fff1f2249e954a7cbe8e608febdb973d0cb752350db8b2047fe7e20d3ad8ab447979b54e295477e112c01148e117108ab27254b9954680eb7af89411877916f1",
          "sha256": "37a420d09438b3e7a3319cd6e8f49623610f56b4e51e014d2966c51640d5e712",
          "sha1": "ea65a4e1cc3ea3bc44a93df978ce8403574ecd3a",
          "md5": "11e1cc41a97503ab7e9299813d13c09c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "printer-jvm-2.2.0-sources.jar",
          "url": "printer-jvm-2.2.0-sources.jar",
          "size": 46189,
          "sha512": "ae88f91748e0ab3ece1c19ed374c38929465a55dcecfad79024755f636615b4e4bc81c969a639d11a545659a8459ccac619638157733b475976c11c8c256b361",
          "sha256": "5e18e0ffba4b28bdd28976ec57ed71f34f9d8edafa768a0427e3e8671c0f2d78",
          "sha1": "84f37d98a67678334c3bf25ea2fbcf22eedff07c",
          "md5": "9b022d5a6d741b585c946aee224e8910"
        }
      ]
    }
  ]
}
