{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.8/kmp_printer-2.3.8.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-jvm-2.3.8.jar",
          "url": "kmp_printer-jvm-2.3.8.jar",
          "size": 648724,
          "sha512": "5030b796f05b8d180db2696212bfa2ff2f2285a92142e29bc2c697d0c4730b963b605071fc086c2c7a06f8b18e53a5139aa1057e009893e1b308ced19d69031a",
          "sha256": "78184d929ab52cfa7cca3a675f97a80a3dada34bda165af97d1a48a60176fa3a",
          "sha1": "5dec6395b9ce79a5b199d87f23a919aacdf01f19",
          "md5": "1dcb43152eb4b2c428dde9e03b8f76c8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.usb4java",
          "module": "usb4java",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.usb4java",
          "module": "libusb4java",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-jvm-2.3.8.jar",
          "url": "kmp_printer-jvm-2.3.8.jar",
          "size": 648724,
          "sha512": "5030b796f05b8d180db2696212bfa2ff2f2285a92142e29bc2c697d0c4730b963b605071fc086c2c7a06f8b18e53a5139aa1057e009893e1b308ced19d69031a",
          "sha256": "78184d929ab52cfa7cca3a675f97a80a3dada34bda165af97d1a48a60176fa3a",
          "sha1": "5dec6395b9ce79a5b199d87f23a919aacdf01f19",
          "md5": "1dcb43152eb4b2c428dde9e03b8f76c8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmp_printer-jvm-2.3.8-sources.jar",
          "url": "kmp_printer-jvm-2.3.8-sources.jar",
          "size": 196251,
          "sha512": "5e4d3892128195f498737df9fca7a56c94757580d618cb0dfe57694095e2b088c95f6f20d38876e99b62cf24a5ddc3bd4ff73ed9bd63eadeda0dff510cffefea",
          "sha256": "adb35e1307f482734ac81e2bba16ca89dd6683e3e06ffe46c3f62b8eaa593f49",
          "sha1": "d1df02e4a0b7bdc0933b5659a45552cf8e35afd3",
          "md5": "c3c0a4451b42af8a4f7cdc3e55d0e76b"
        }
      ]
    }
  ]
}
