{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/2.3.2/printer-2.3.2.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosSimulatorArm64Main-2.3.2.klib",
          "url": "printer-iossimulatorarm64-2.3.2.klib",
          "size": 300836,
          "sha512": "fa9b0f7b46e49e18cc6dc4236b8fc21426522ecc529115ef31f4ae218cc54d6fab512d6582d68f6580076667bd34b8c8a2c612faeab44096d49ef5eadca4ae89",
          "sha256": "6329aa888392abd3f774bc2876e1d37e4fa4d7afe5db7165cdbf1b0bc769e11c",
          "sha1": "a24d742fa59190275d0355235f41791f072029e3",
          "md5": "3cd09975bc6a37d1cd4b868a910f156b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "printer-iossimulatorarm64-2.3.2-sources.jar",
          "url": "printer-iossimulatorarm64-2.3.2-sources.jar",
          "size": 60936,
          "sha512": "c963e343f1fced87af6fdc095a538f586d7edbde876775220bdfb8f02ea46665a1440498cc7a1b9e8ae90bfe3d13237d26b1841841cd6e84c8653c98c2e43bcf",
          "sha256": "165df4e4097f92bca92df535f83b4e5c9d60de56f31f5a2ddffef9ebcaf38220",
          "sha1": "ee60f9be52aff1681b493f7e65bfda8c36ffce3b",
          "md5": "e30662f3e53cc9bc2deb9914692a4320"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iossimulatorarm64-2.3.2-metadata.jar",
          "url": "printer-iossimulatorarm64-2.3.2-metadata.jar",
          "size": 6848,
          "sha512": "2cc9894be6b9db3b8f1ddf25239cd02bd3501f89e25b44389c9b4cdaa397ff9fcc394d3b9f2f1042cc7deb54d8aeeb5c9f9828a3c5d3ef9f67f0a69f8a7c6009",
          "sha256": "e70c4c34d997fd3943e7a06d5099a67e56dd96f1720ee5e1514a442b1324d247",
          "sha1": "ca5c171b1eaaa59c84c880b753e1074f9639cb2a",
          "md5": "676de100a29f4707be1a47d83fe1e040"
        }
      ]
    }
  ]
}
