{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.6/kmp_printer-2.3.6.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-release.aar",
          "url": "kmp_printer-android-2.3.6.aar",
          "size": 359881,
          "sha512": "dda87e481b24854462d46210d3edf9b90258279aaf104b6424c070d508406ea7812638f63bc4bca974038a9d6c70c636afe9028dc5ce845ed334dd535efe308f",
          "sha256": "54cb6c3fcc92d63474cb49443fa9cda0afec0d15d5d27cab9c5e941b0552d068",
          "sha1": "914a2d21d196ef5cd26fdbb99b3af441eeb1733c",
          "md5": "7ecbef1d2e9bdea6fff8e16f74abd3e7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmp_printer-release.aar",
          "url": "kmp_printer-android-2.3.6.aar",
          "size": 359881,
          "sha512": "dda87e481b24854462d46210d3edf9b90258279aaf104b6424c070d508406ea7812638f63bc4bca974038a9d6c70c636afe9028dc5ce845ed334dd535efe308f",
          "sha256": "54cb6c3fcc92d63474cb49443fa9cda0afec0d15d5d27cab9c5e941b0552d068",
          "sha1": "914a2d21d196ef5cd26fdbb99b3af441eeb1733c",
          "md5": "7ecbef1d2e9bdea6fff8e16f74abd3e7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmp_printer-android-2.3.6-sources.jar",
          "url": "kmp_printer-android-2.3.6-sources.jar",
          "size": 72273,
          "sha512": "46db4d4fb6c5404a061ddaedec4aaf17c50d068528d67d311c9c54272695bdeda66d04f741f4ca928429ae9ddf9f82d93c3a0e1417033c3c5c82e6490cdfd711",
          "sha256": "3a56a8421592b92dbc84667664c1a061d21f3d635558d651da2a911f38f43024",
          "sha1": "8f600145b90510e1e6ce4bdfb0dda8161e36de05",
          "md5": "0ca95860ccc3102a0ab9ff2216d21cc5"
        }
      ]
    }
  ]
}
