package ngga.ring.label

import ngga.ring.printer.KmpPrinter
import ngga.ring.printer.model.PrinterConfig
import ngga.ring.printer.model.PrintStatus
import kotlinx.coroutines.flow.first

/**
 * High-level label printer that combines connection (via [KmpPrinter])
 * with label generation (ZPL / Brother QL / etc.).
 *
 * Usage:
 * ```kotlin
 * val labelPrinter = LabelPrinter()
 *
 * // Connect to a Zebra printer via TCP
 * labelPrinter.connect(
 *     name = "Warehouse Zebra",
 *     address = "192.168.1.200",
 *     port = 9100
 * )
 *
 * // Build and print a label
 * val zpl = ZplBuilder().apply {
 *     labelSize = LabelSize.ZEBRA_4X6
 *     text("TOKO ABC", bold = true)
 *     barcode("BRG-001", BarcodeFormat.CODE_128)
 *     price("25.000")
 * }.build()
 *
 * labelPrinter.printLabel(zpl)
 * labelPrinter.disconnect()
 * ```
 */
public class LabelPrinter(
    private val printer: KmpPrinter = KmpPrinter()
) {
    private var lastConfig: PrinterConfig? = null

    /** Whether the underlying printer is currently connected. */
    public val isConnected: Boolean
        get() = lastConfig != null

    /**
     * Connect to a label printer.
     *
     * @param name Human-readable printer name.
     * @param connectionType One of: "NETWORK", "BLUETOOTH", "USB", "SERIAL".
     * @param address IP/MAC/device path. Null for auto-discovery.
     * @param port Port number (default: 9100 for TCP/IP).
     * @param timeoutMs Connection timeout in milliseconds (default: 5000).
     * @return true if connection succeeded.
     */
    public suspend fun connect(
        name: String,
        connectionType: String = "NETWORK",
        address: String? = null,
        port: Int = 9100,
        timeoutMs: Int = 5000
    ): Boolean {
        val config = PrinterConfig(
            name = name,
            connectionType = connectionType,
            address = address,
            port = port,
            connectionTimeoutMs = timeoutMs
        )
        return connect(config)
    }

    /**
     * Connect using a pre-built [PrinterConfig].
     */
    public suspend fun connect(config: PrinterConfig): Boolean {
        val status = printer.testConnection(config)
        return if (status is PrintStatus.Success) {
            lastConfig = config
            true
        } else {
            lastConfig = null
            false
        }
    }

    /**
     * Send raw label data (generated by [ZplBuilder], [BrotherQlBuilder],
     * or any custom protocol builder) to the connected printer.
     *
     * @param labelData Raw bytes of the label command(s).
     * @return [PrintStatus.Success] or [PrintStatus.Error].
     */
    public suspend fun printLabel(labelData: ByteArray): PrintStatus {
        val config = lastConfig
            ?: return PrintStatus.Error("Not connected. Call connect() first.")

        return try {
            val result = printer.printRaw(config, labelData)
                .first { it !is PrintStatus.Processing }
            result
        } catch (e: Exception) {
            PrintStatus.Error("Print failed: ${e.message}")
        }
    }

    /**
     * Convenience: build a label with [ZplBuilder] and print it in one call.
     */
    public suspend fun printZpl(builder: ZplBuilder.() -> Unit): PrintStatus {
        val zpl = ZplBuilder().apply(builder).build()
        return printLabel(zpl)
    }

    /**
     * Convenience: build a label with [BrotherQlBuilder] and print it in one call.
     */
    public suspend fun printBrother(builder: BrotherQlBuilder.() -> Unit): PrintStatus {
        val data = BrotherQlBuilder().apply(builder).build()
        return printLabel(data)
    }

    /**
     * Build and print a generic [LabelData].
     */
    public suspend fun printLabel(label: LabelData, protocol: LabelProtocol): PrintStatus {
        val bytes = when (protocol) {
            LabelProtocol.ZPL -> {
                ZplBuilder().apply {
                    labelSize = label.labelSize
                    elements.addAll(label.elements)
                }.build()
            }
            LabelProtocol.BROTHER_QL -> {
                BrotherQlBuilder().apply {
                    labelSize = label.labelSize
                    elements.addAll(label.elements)
                }.build()
            }
            LabelProtocol.BROTHER_TD,
            LabelProtocol.CPCL -> {
                // Placeholder — future support
                return PrintStatus.Error("$protocol support coming soon")
            }
        }
        return printLabel(bytes)
    }

    /**
     * Disconnect from the printer.
     */
    public suspend fun disconnect() {
        try {
            printer.disconnect()
        } catch (_: Exception) { /* ignore */ }
        lastConfig = null
    }
}
