{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.5/kmp_printer-2.3.5.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-release.aar",
          "url": "kmp_printer-android-2.3.5.aar",
          "size": 343027,
          "sha512": "2b5a44a3c629118d3c768e6858e48e617423ec663f0c2ba0757fe3474d573bc02aa60028463c70b00a90961ec3b961628a54195aa20018eb1262e6e12b4076f8",
          "sha256": "f5a1ab3c83f147bc24e7157451a7e64d5c21ea3820f8b3fcf4489dd46171e71e",
          "sha1": "84d6e8cc164878e5aea83992b0781021fc99f153",
          "md5": "3204daba3fa2f8e6af956e2264d55ffc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmp_printer-release.aar",
          "url": "kmp_printer-android-2.3.5.aar",
          "size": 343027,
          "sha512": "2b5a44a3c629118d3c768e6858e48e617423ec663f0c2ba0757fe3474d573bc02aa60028463c70b00a90961ec3b961628a54195aa20018eb1262e6e12b4076f8",
          "sha256": "f5a1ab3c83f147bc24e7157451a7e64d5c21ea3820f8b3fcf4489dd46171e71e",
          "sha1": "84d6e8cc164878e5aea83992b0781021fc99f153",
          "md5": "3204daba3fa2f8e6af956e2264d55ffc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmp_printer-android-2.3.5-sources.jar",
          "url": "kmp_printer-android-2.3.5-sources.jar",
          "size": 69140,
          "sha512": "9eb95f4ecc41d3f981962b423edbdb1a2d977f3618d52c7c29d20412aaa7b3140523603cafc3b7b691c052c1359158f63c270da5aadd107403a6ddfd1448838a",
          "sha256": "d61faec340f169e7d27c183a63a6a6b41e91f90fa3c58933d4a828c88436ae75",
          "sha1": "be96bc9f9599fbdfd6df705d52db0c567a78d57c",
          "md5": "e72f80527713441ec860559c1c3193f7"
        }
      ]
    }
  ]
}
