{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/2.3.3/printer-2.3.3.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosArm64Main-2.3.3.klib",
          "url": "printer-iosarm64-2.3.3.klib",
          "size": 300777,
          "sha512": "da5e93508268546925addfb25725170ef17e53cf1c64a353ca3555f5f4cf3f0f34e81a988f5b1a12b1cfc3989533b75e834c2e0c7e199bb5315d17b1fa7b4c48",
          "sha256": "3d7d686697f48d4fb49ac6b6c91801cb6bd97c55af82ad9dc3181d968fa3410c",
          "sha1": "0f49759dbd7a9fceba9e3e934b21a44dc17e337e",
          "md5": "b86ecf41109b6ac07499ab1133977127"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmp_printer-iosarm64-2.3.3-sources.jar",
          "url": "printer-iosarm64-2.3.3-sources.jar",
          "size": 60936,
          "sha512": "c963e343f1fced87af6fdc095a538f586d7edbde876775220bdfb8f02ea46665a1440498cc7a1b9e8ae90bfe3d13237d26b1841841cd6e84c8653c98c2e43bcf",
          "sha256": "165df4e4097f92bca92df535f83b4e5c9d60de56f31f5a2ddffef9ebcaf38220",
          "sha1": "ee60f9be52aff1681b493f7e65bfda8c36ffce3b",
          "md5": "e30662f3e53cc9bc2deb9914692a4320"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-iosarm64-2.3.3-metadata.jar",
          "url": "printer-iosarm64-2.3.3-metadata.jar",
          "size": 6855,
          "sha512": "f64c4ba053fe292d2eabce59df42f87bf81098de026b41009cb99f10e9fac91754e71097303bf682121a9c6008561c9d2485d5c3ca8af192e17da1c4f9f99449",
          "sha256": "cd1c36c6e3d0991bb4c4bf4c400a176e27c7ef701bade365ae3731d74f32884b",
          "sha1": "54f6887442d7f810e5bce262db1e83e5cdfbc5c0",
          "md5": "2654cad751854946779695ac3cae7227"
        }
      ]
    }
  ]
}
