{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.6/kmp_printer-2.3.6.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-jvm-2.3.6.jar",
          "url": "kmp_printer-jvm-2.3.6.jar",
          "size": 470115,
          "sha512": "c7a0b875081a562b8f9282f001ae8295290a4121a775768d9b00021020edb5d64cb7bac4ef2626cd640867ad4ea7cca5a73a80e26d1d528f044f4b53155d704f",
          "sha256": "3ef632787fee8fc77a56a5a03e8bac78ebf52b49ea64eab6fb5a65fa37bad655",
          "sha1": "120f259d7ccb5992862867ec72f33f8faf9c2ecd",
          "md5": "b8217e7a778dd29820821f1020325a70"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.usb4java",
          "module": "usb4java",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.usb4java",
          "module": "libusb4java",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-jvm-2.3.6.jar",
          "url": "kmp_printer-jvm-2.3.6.jar",
          "size": 470115,
          "sha512": "c7a0b875081a562b8f9282f001ae8295290a4121a775768d9b00021020edb5d64cb7bac4ef2626cd640867ad4ea7cca5a73a80e26d1d528f044f4b53155d704f",
          "sha256": "3ef632787fee8fc77a56a5a03e8bac78ebf52b49ea64eab6fb5a65fa37bad655",
          "sha1": "120f259d7ccb5992862867ec72f33f8faf9c2ecd",
          "md5": "b8217e7a778dd29820821f1020325a70"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmp_printer-jvm-2.3.6-sources.jar",
          "url": "kmp_printer-jvm-2.3.6-sources.jar",
          "size": 84022,
          "sha512": "15e660d32224414656c896feb473bbebad21cd5a2f8deb5ad422628ab0fdc9366307a55fa9d0c30bd9b8d8ede17b7af8496446e02545bdfe10c25ab9d3e4ca10",
          "sha256": "8b0e1e37184b28afbef3b546c3cd7d5372fb247603eca05f9a6b925960ecaa1a",
          "sha1": "0cd6b98cb33ac78018fa8e8fdf7c0a9787363332",
          "md5": "890adaf885be724195ccea5251f98a6d"
        }
      ]
    }
  ]
}
