{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.6/kmp_printer-2.3.6.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-linuxArm64Main-2.3.6.klib",
          "url": "kmp_printer-linuxArm64-2.3.6.klib",
          "size": 292014,
          "sha512": "c40eff2ffba0ef5bbd9089501d99e32afdf9acaec60001546819696d3399b6419e43779a07220bac51279a8a36ed7ced6e09f975c526e250cb111c3e771bebe3",
          "sha256": "7489ea645a67026be41dd4153ac0866d515302d72dc047806641114229118519",
          "sha1": "be1ccbd111972509526a70d7483f9fd251c5d215",
          "md5": "6cf433ded630ec4d96e7a42c33f0a75a"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmp_printer-linuxarm64-2.3.6-sources.jar",
          "url": "kmp_printer-linuxArm64-2.3.6-sources.jar",
          "size": 61374,
          "sha512": "aef58790ef31398622aba57c34ce6e801ea04c052a1d35eb4ddf87cf11ad2a0b1a950357ce41040b1a1e9a7fdece1e93b53555278d36832854ff5eb91a5abbfa",
          "sha256": "1ad8e09f6d4986d9cc30134421d868998d026908da2ee55c72acf43ad7d54fb6",
          "sha1": "6a09779ee910c574c1caf9147579f6f0e8ffdfc5",
          "md5": "9bc80e3b7b6c219bda9aacbaaf20367d"
        }
      ]
    }
  ]
}
