{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/2.3.1/printer-2.3.1.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosSimulatorArm64Main-2.3.1.klib",
          "url": "printer-iossimulatorarm64-2.3.1.klib",
          "size": 300836,
          "sha512": "fa9b0f7b46e49e18cc6dc4236b8fc21426522ecc529115ef31f4ae218cc54d6fab512d6582d68f6580076667bd34b8c8a2c612faeab44096d49ef5eadca4ae89",
          "sha256": "6329aa888392abd3f774bc2876e1d37e4fa4d7afe5db7165cdbf1b0bc769e11c",
          "sha1": "a24d742fa59190275d0355235f41791f072029e3",
          "md5": "3cd09975bc6a37d1cd4b868a910f156b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "printer-iossimulatorarm64-2.3.1-sources.jar",
          "url": "printer-iossimulatorarm64-2.3.1-sources.jar",
          "size": 60936,
          "sha512": "c963e343f1fced87af6fdc095a538f586d7edbde876775220bdfb8f02ea46665a1440498cc7a1b9e8ae90bfe3d13237d26b1841841cd6e84c8653c98c2e43bcf",
          "sha256": "165df4e4097f92bca92df535f83b4e5c9d60de56f31f5a2ddffef9ebcaf38220",
          "sha1": "ee60f9be52aff1681b493f7e65bfda8c36ffce3b",
          "md5": "e30662f3e53cc9bc2deb9914692a4320"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iossimulatorarm64-2.3.1-metadata.jar",
          "url": "printer-iossimulatorarm64-2.3.1-metadata.jar",
          "size": 6848,
          "sha512": "035808dc2ddd4351f3e1f6ed0773031379b12893edc5f1ddf24d055756bc98b2a0a6174a1b1be9321707ca73349f282d9b6c4b090b1e121024c73bcb9734629f",
          "sha256": "322d9f615b2709293955f8bc8432ca4ab60f86ecef18244a678852f0c6fcf267",
          "sha1": "238fe51971d0373aad71d5cd1a3a88324a6b69f8",
          "md5": "e9924def0d99074d4bf1c65bc5caa150"
        }
      ]
    }
  ]
}
