// Generated by @nuxt/scripts
declare module '#app' {
  interface NuxtApp {
    $scripts: Record<string, import('#nuxt-scripts/types').UseScriptContext<any> | undefined>
    _scripts: Record<string, import('#nuxt-scripts/types').NuxtDevToolsScriptInstance>
  }
  interface RuntimeNuxtHooks {
    'scripts:updated': (ctx: { scripts: Record<string, import('#nuxt-scripts/types').NuxtDevToolsScriptInstance> }) => void | Promise<void>
  }
}

export {}