{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.6/kmp_printer-2.3.6.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosArm64Main-2.3.6.klib",
          "url": "printer-iosarm64-2.3.6.klib",
          "size": 321747,
          "sha512": "4916dfd2d104ce06144aaa9ba14febfc41c669ca1311499b97eb7c14bd9357d327534c86a4292ef88d60e96d2665ea1441655b31fbe50db02516bc9adcb00815",
          "sha256": "9220e9ad65244767673f692dfcfef5d94ef90d95654cdeeb1036445bd064ac73",
          "sha1": "971d193b10f76e59ddec116a5f8ead2a7df18624",
          "md5": "670b783cc85a3ce7015d32633c511802"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmp_printer-iosarm64-2.3.6-sources.jar",
          "url": "printer-iosarm64-2.3.6-sources.jar",
          "size": 64069,
          "sha512": "747ce6de669fb7e2b855cacc0bdb45c8300399c12fd47edc8675ce343b05472c05adf4758dd1b09f9e9aeb1e6fede4d1f46bd9fcded7d4f67fd0864147262537",
          "sha256": "3587f4bf48de3b1bc811f03f28ff763bc4fd3884788a0cd82a855150ba430473",
          "sha1": "ef362163fdfcf89ce82ed79501b903183a0c1eb6",
          "md5": "7aa8cd7fd1f9ff847a2d1f9927d55b14"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-iosarm64-2.3.6-metadata.jar",
          "url": "printer-iosarm64-2.3.6-metadata.jar",
          "size": 6855,
          "sha512": "1709cf689d4cf2fed0c141a61bf01b1bd7daba81561ebab8a7c4b457ccbc8e24dbfa97d95943f860736ff3d4b0ceefc39198afb1912c5291081a581412ce670b",
          "sha256": "6e0158a9994b4a8c64a83d208036a6988b2885f66b5ce003d0b73a5cc6bfae24",
          "sha1": "3c08a972ffda68c16c37bc5f62e886636034f00a",
          "md5": "cc96e23ceb7aa8fe11d04a624fd51c78"
        }
      ]
    }
  ]
}
