<template>
  <div class="container mx-auto px-4 py-20">
    <div class="max-w-2xl mb-16">
      <div class="enterprise-badge mb-2">Visual Output</div>
      <h1 class="text-5xl font-black tracking-tight mb-4">Gallery</h1>
      <p class="text-slate-500 dark:text-slate-400">Sample receipts generated by the KmpPrinter engine.</p>
    </div>

    <div class="grid md:grid-cols-2 gap-12">
      <!-- Standard Receipt -->
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-bold">Standard Retail</h3>
          <UBadge color="blue" variant="solid">58mm</UBadge>
        </div>
        <div class="bg-white p-8 rounded-xl shadow-2xl border border-slate-200 text-slate-900 font-mono text-[10px] leading-tight max-w-[280px] mx-auto">
          <div class="text-center font-bold text-base mb-2">RETAIL COFFEE</div>
          <div class="text-center mb-4">Kuningan, Jakarta</div>
          <div class="flex justify-between border-b border-dashed border-slate-300 pb-1 mb-2">
            <span>INV#001</span>
            <span>08/05/26</span>
          </div>
          <div class="flex justify-between mb-1">
            <span class="w-1/2">Americano</span>
            <span class="w-1/4 text-center">x1</span>
            <span class="w-1/4 text-right">25.000</span>
          </div>
          <div class="flex justify-between mb-1">
            <span class="w-1/2">Donut Glazed</span>
            <span class="w-1/4 text-center">x2</span>
            <span class="w-1/4 text-right">30.000</span>
          </div>
          <div class="border-t border-dashed border-slate-300 mt-4 pt-2 flex justify-between font-bold text-sm">
            <span>TOTAL</span>
            <span>55.000</span>
          </div>
          <div class="text-center mt-8 pt-4 border-t border-slate-100">
            TERIMA KASIH
          </div>
        </div>
      </div>

      <!-- Expert Invoice -->
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-bold">Expert Invoice</h3>
          <UBadge color="green" variant="solid">80mm</UBadge>
        </div>
        <div class="bg-white p-10 rounded-xl shadow-2xl border border-slate-200 text-slate-900 font-mono text-xs leading-tight max-w-[360px] mx-auto">
          <div class="text-center font-black text-xl mb-6">INVOICE</div>
          <div class="flex justify-between mb-1">
            <span class="text-slate-400 uppercase text-[10px] font-bold">Customer</span>
            <span class="font-bold">John Doe Enterprise</span>
          </div>
          <div class="flex justify-between mb-4">
            <span class="text-slate-400 uppercase text-[10px] font-bold">Status</span>
            <span class="text-green-600 font-bold">PAID</span>
          </div>
          
          <div class="bg-slate-50 p-2 font-bold flex justify-between text-[10px] mb-2">
            <span class="flex-grow">DESCRIPTION</span>
            <span class="w-20 text-right">AMOUNT</span>
          </div>
          <div class="px-2 space-y-2">
            <div class="flex justify-between">
              <span class="flex-grow">Cloud Subscription (Annual)</span>
              <span class="w-20 text-right">1.200.000</span>
            </div>
            <div class="flex justify-between">
              <span class="flex-grow">Setup & Integration</span>
              <span class="w-20 text-right">500.000</span>
            </div>
          </div>
          
          <div class="mt-10 border-t-2 border-black pt-4 flex justify-between font-black text-base">
            <span>GRAND TOTAL</span>
            <span>1.700.000</span>
          </div>
          
          <div class="flex justify-center mt-10">
            <UIcon name="i-heroicons-qr-code" class="w-20 h-20" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
