{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/2.3.0/printer-2.3.0.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "printer-jvm-2.3.0.jar",
          "url": "printer-jvm-2.3.0.jar",
          "size": 451893,
          "sha512": "4f8890f8ec04a2255dabe7ea9441fd27d904ac07cf07c50ee48e977f77ca9245ec7bb0e535a8b6f0042e1744d022417526ed5e6b1c6faeb8c524a4d200eb6046",
          "sha256": "789ef61e07a0f106f05d192180494cc2b4d3fda5211d78ed61c2ed69126f10c5",
          "sha1": "d588ed053f25fe0459bc8fb5f64d4b50eb0a425b",
          "md5": "ec11987b1fdf415ebec00432995b0800"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.usb4java",
          "module": "usb4java",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.usb4java",
          "module": "libusb4java",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-jvm-2.3.0.jar",
          "url": "printer-jvm-2.3.0.jar",
          "size": 451893,
          "sha512": "4f8890f8ec04a2255dabe7ea9441fd27d904ac07cf07c50ee48e977f77ca9245ec7bb0e535a8b6f0042e1744d022417526ed5e6b1c6faeb8c524a4d200eb6046",
          "sha256": "789ef61e07a0f106f05d192180494cc2b4d3fda5211d78ed61c2ed69126f10c5",
          "sha1": "d588ed053f25fe0459bc8fb5f64d4b50eb0a425b",
          "md5": "ec11987b1fdf415ebec00432995b0800"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "printer-jvm-2.3.0-sources.jar",
          "url": "printer-jvm-2.3.0-sources.jar",
          "size": 80889,
          "sha512": "019f7b40cc8a056dca0e36ffcd72a2526efb5504760a1c0d550dc5e2d870b5b7be02bc00f00447370fd6b848f580f9830c2337f49f95330a843a08f9f529e54d",
          "sha256": "498417aba7617ac2e6b4e11e55447c5f530b78ad704f847c9ed3160c48a1a00f",
          "sha1": "01a6aaad9b65dd0424d784d1948716c1340f7e8f",
          "md5": "7d9c2fabcf6cbbb24a07e4c61d2c4fe1"
        }
      ]
    }
  ]
}
