{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/2.3.0/printer-2.3.0.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "printer-wasm-js-2.3.0.klib",
          "url": "printer-wasm-js-2.3.0.klib",
          "size": 258288,
          "sha512": "b2f3d8f0863656e2886a8244c5c82989aa153d74e7e4317934fd912d3698d6e2a49ceda17e7ebc14cf216bc00f3f841ca95e190fd860505ed4de101cdfac12d7",
          "sha256": "053ab00b4a729e3bb7f8bccca7fb59c2c4ae5dd2fdcf4980223573a57f7170a1",
          "sha1": "541caa656c715bd4efd60734da4d96b033e5c098",
          "md5": "4a0f18abc9f68719fc04000553cdd7cd"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-wasm-js-2.3.0.klib",
          "url": "printer-wasm-js-2.3.0.klib",
          "size": 258288,
          "sha512": "b2f3d8f0863656e2886a8244c5c82989aa153d74e7e4317934fd912d3698d6e2a49ceda17e7ebc14cf216bc00f3f841ca95e190fd860505ed4de101cdfac12d7",
          "sha256": "053ab00b4a729e3bb7f8bccca7fb59c2c4ae5dd2fdcf4980223573a57f7170a1",
          "sha1": "541caa656c715bd4efd60734da4d96b033e5c098",
          "md5": "4a0f18abc9f68719fc04000553cdd7cd"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "printer-wasm-js-2.3.0-sources.jar",
          "url": "printer-wasm-js-2.3.0-sources.jar",
          "size": 57821,
          "sha512": "cda4308775ffa62230953884819f3541f287128cec75050177f0a41f8e57d0c5f8b75a3a7e58303fb7d7dea26095efd57319bfaab154f12c9104f97c14ba6158",
          "sha256": "d47eae9e4f4e2474a02a4bc34977ebaa2c2f7653ba38385608f041b61cae479e",
          "sha1": "7923b03dfda730f95a697d30f928b40f6027c7de",
          "md5": "5a6c565d6baf338223ffce5d8f8cf31a"
        }
      ]
    }
  ]
}
