{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.3/kmp_printer-2.3.3.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosSimulatorArm64Main-2.3.3.klib",
          "url": "printer-iossimulatorarm64-2.3.3.klib",
          "size": 300842,
          "sha512": "a1ad30fa06184f3c4339331a6839a7df9875ee49230cad6936557610d4153c72614443c1a754478878e3b53307a8b015fe8dacc270b15ef08956685ce5c3de6c",
          "sha256": "ce863a78686f2f828785674d478821bc051d1748b6548a3a0b8b99b0e78f09bc",
          "sha1": "3d47a37b7b44c79e9fd2495926fffda0b6f901fb",
          "md5": "27496fab4481ce5f708cf9b88479d3cc"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmp_printer-iossimulatorarm64-2.3.3-sources.jar",
          "url": "printer-iossimulatorarm64-2.3.3-sources.jar",
          "size": 60936,
          "sha512": "c963e343f1fced87af6fdc095a538f586d7edbde876775220bdfb8f02ea46665a1440498cc7a1b9e8ae90bfe3d13237d26b1841841cd6e84c8653c98c2e43bcf",
          "sha256": "165df4e4097f92bca92df535f83b4e5c9d60de56f31f5a2ddffef9ebcaf38220",
          "sha1": "ee60f9be52aff1681b493f7e65bfda8c36ffce3b",
          "md5": "e30662f3e53cc9bc2deb9914692a4320"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-iossimulatorarm64-2.3.3-metadata.jar",
          "url": "printer-iossimulatorarm64-2.3.3-metadata.jar",
          "size": 6855,
          "sha512": "c2df1d8232e478609794dece9559490bed8574104563a950e6874f069f71c7f5ca430f875e055182383c435ee0581ac44f397a52efbf7d63b532cf2fb70b8762",
          "sha256": "180ad7eea15a9953e8248ab71d0b379727016d0023ecb7591867c7fe2534b8ad",
          "sha1": "c9b5a188598a0beabf7fa0cf51f4c1e82af490b2",
          "md5": "85b91cbe5c31c91c91191694841c83ce"
        }
      ]
    }
  ]
}
