{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.8/kmp_printer-2.3.8.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-js-2.3.8.klib",
          "url": "kmp_printer-js-2.3.8.klib",
          "size": 435904,
          "sha512": "0c6b4860b37fa3fbe9cf9a189d012da67e63b72baba2b488b60554b6405b98e512ca464702bd4a74a3a00927213cf3e3b49cee95b488f661880d57a548312c23",
          "sha256": "ac63e61cc933ab5aae847d20391956df60aa1997b2733d09f85c3e9dc56214ec",
          "sha1": "4933a5b2a2bcb8920030eb6e2f33446c56cb500c",
          "md5": "119eae502e9ea7fe0c86eb770962e0c6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-js-2.3.8.klib",
          "url": "kmp_printer-js-2.3.8.klib",
          "size": 435904,
          "sha512": "0c6b4860b37fa3fbe9cf9a189d012da67e63b72baba2b488b60554b6405b98e512ca464702bd4a74a3a00927213cf3e3b49cee95b488f661880d57a548312c23",
          "sha256": "ac63e61cc933ab5aae847d20391956df60aa1997b2733d09f85c3e9dc56214ec",
          "sha1": "4933a5b2a2bcb8920030eb6e2f33446c56cb500c",
          "md5": "119eae502e9ea7fe0c86eb770962e0c6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kmp_printer-js-2.3.8-sources.jar",
          "url": "kmp_printer-js-2.3.8-sources.jar",
          "size": 175213,
          "sha512": "9f8c53448b40092a54e2d4467a39a86e83fcae323bd54dea4568cdc923ed12f1f4e121652f431737b834c3e90f707f6239a4d6c06d1d1ce6f8d9199aeb408cac",
          "sha256": "6e0c6ef67d798a8492636683fc2aa6cdc2e827037d41639afd60913553c3fbca",
          "sha1": "377b7ed4dfd3f3e827262952abfcd026c830b6bc",
          "md5": "ef9c39f1afe5390fe064407ea261ef1a"
        }
      ]
    }
  ]
}
