{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-metadata-2.2.0.jar",
          "url": "printer-2.2.0.jar",
          "size": 26853,
          "sha512": "3587d2295a8e1e29cdf6080d41cb1ec393a398f6bd2b4ca633968bb227249b51e1be5b6b831f8965784a1bb585735d3ecd45ac0ef8f50066c2c4e7c793e55f8e",
          "sha256": "cdf80331b9a1d361d44cb25b469d0751f0b976354b430ad9eeb6a88b6e4e97df",
          "sha1": "a35834cf78d878686308a0d1b1caff7f9c816060",
          "md5": "634af4e17da656aae30fe42b45f93e88"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "printer-kotlin-2.2.0-sources.jar",
          "url": "printer-2.2.0-sources.jar",
          "size": 47217,
          "sha512": "f63798737e653150698c337d6f736243ce4e69d1805e2ad4783c46f5eed9b1be0e9abe2ef7d856384b9b7463269175987e559d8604a405fb860dcab9ddd3a0c6",
          "sha256": "c1db05f369e331505e5f622a02d4d71422aa1c3260c923c345ae795ab0af8222",
          "sha1": "41f41fb132f3ab8651a4b254e4272b651c84d184",
          "md5": "c7a1b80649a15904161574cb8c79d397"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../printer-android/2.2.0/printer-android-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-android",
        "version": "2.2.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../printer-android/2.2.0/printer-android-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-android",
        "version": "2.2.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../printer-android/2.2.0/printer-android-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-android",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printer-iosarm64/2.2.0/printer-iosarm64-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-iosarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printer-iosarm64/2.2.0/printer-iosarm64-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-iosarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printer-iosarm64/2.2.0/printer-iosarm64-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-iosarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printer-iossimulatorarm64/2.2.0/printer-iossimulatorarm64-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-iossimulatorarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printer-iossimulatorarm64/2.2.0/printer-iossimulatorarm64-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-iossimulatorarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../printer-iossimulatorarm64/2.2.0/printer-iossimulatorarm64-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-iossimulatorarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../printer-js/2.2.0/printer-js-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-js",
        "version": "2.2.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../printer-js/2.2.0/printer-js-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-js",
        "version": "2.2.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../printer-js/2.2.0/printer-js-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-js",
        "version": "2.2.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../printer-jvm/2.2.0/printer-jvm-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-jvm",
        "version": "2.2.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../printer-jvm/2.2.0/printer-jvm-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-jvm",
        "version": "2.2.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../printer-jvm/2.2.0/printer-jvm-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-jvm",
        "version": "2.2.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../printer-wasm-js/2.2.0/printer-wasm-js-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-wasm-js",
        "version": "2.2.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../printer-wasm-js/2.2.0/printer-wasm-js-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-wasm-js",
        "version": "2.2.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../printer-wasm-js/2.2.0/printer-wasm-js-2.2.0.module",
        "group": "io.github.ringga-dev",
        "module": "printer-wasm-js",
        "version": "2.2.0"
      }
    }
  ]
}
