{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp_printer/2.3.8/kmp_printer-2.3.8.module",
    "group": "io.github.ringga-dev",
    "module": "kmp_printer",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmp_printer-release.aar",
          "url": "kmp_printer-android-2.3.8.aar",
          "size": 531949,
          "sha512": "80957f9200f51b989ec851f867427d1d66dd26f81195a131eb292daf454c3c2feda79aa408a6d2bacb82b033a74b5c6e95b8b6ec8fb84e4704efaed572c5afc3",
          "sha256": "38a4dcce7035122029428d68c9e9b376943e538aba803f659243a2d692804e43",
          "sha1": "6d8b9304d804857266c047bea67c74d4c1a1046a",
          "md5": "1e38dfa0cce7bd9cd815e88caf54c00f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmp_printer-release.aar",
          "url": "kmp_printer-android-2.3.8.aar",
          "size": 531949,
          "sha512": "80957f9200f51b989ec851f867427d1d66dd26f81195a131eb292daf454c3c2feda79aa408a6d2bacb82b033a74b5c6e95b8b6ec8fb84e4704efaed572c5afc3",
          "sha256": "38a4dcce7035122029428d68c9e9b376943e538aba803f659243a2d692804e43",
          "sha1": "6d8b9304d804857266c047bea67c74d4c1a1046a",
          "md5": "1e38dfa0cce7bd9cd815e88caf54c00f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmp_printer-android-2.3.8-sources.jar",
          "url": "kmp_printer-android-2.3.8-sources.jar",
          "size": 184739,
          "sha512": "165a8deb4592d1c9effdacbf7603b3d109707f76184c5a85b0b02afbd311bbd9cd71f00a10068eb97916eacd4dc9496e8d1be19780576d429395d14753f0eaba",
          "sha256": "0591819f9ee0aed39566a3cff2cb48ef03050964ebc5c6b86f9fd35b53ae2fe3",
          "sha1": "6da5903cc569211a74a34a1295b045eeb935b757",
          "md5": "0a2dcc45649b7df65ab3b96b4954e819"
        }
      ]
    }
  ]
}
